name: Build Windows EXE

on:
  workflow_dispatch: {}   # 只手動觸發，不會每次 push 都跑

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile --name api_extractor extract_api_spec.py
        shell: pwsh

      - name: Upload artifact (exe)
        uses: actions/upload-artifact@v4
        with:
          name: api_extractor-windows
          path: dist/api_extractor.exe
          if-no-files-found: error

